[
{
"device"="desirec",
"base"="1.3.1",
"version"=07-31,
"date"="07-31",
"name"="OMFGB_desirec-1.3.1_nightly-07-31.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.1_nightly-07-31.zip",
"installable"="false",
"description"="Droid X added. Added 1% battery increments since last DX beta. New Launcher speed tweak from Jt1134. In call audio tweaks to Tunderbolt. Fix Fascinate wifi?"
},
{
"device"="desirec",
"base"="1.3.1",
"version"=07-30,
"date"="07-30",
"name"="OMFGB_desirec-1.3.1_nightly-07-30.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.1_nightly-07-30.zip",
"installable"="false",
"description"="4G LTE Toggle included. Broken MMS fixed."
},
{
"device"="desirec",
"base"="1.3.1",
"version"=07-28,
"date"="07-28",
"name"="OMFGB_desirec-1.3.1_nightly-07-28.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.1_nightly-07-28.zip",
"installable"="false",
"description"="Update to OMFGB 1.3.1. Update to Android 2.3.5. Fix wifi tether for applicable devices. Fixes for Google apps instalation issues for Sholes."
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-25,
"date"="07-25",
"name"="OMFGB_desirec-1.3.0_nightly-07-25.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-25.zip",
"installable"="false",
"description"="Updates for Mecha data, notification light while charging. Add Showcase and Mesmerize builds. Fix God mode related FCs. New features to God Mode."
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-24,
"date"="07-24",
"name"="OMFGB_desirec-1.3.0_nightly-07-24.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-24.zip",
"installable"="false",
"description"="We did stuff."
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-23,
"date"="07-23",
"name"="OMFGB_desirec-1.3.0_nightly-07-23.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-23.zip",
"installable"="false",
"description"="You MUST manually wipe /system BEFORE flashing tonights build. God Mode enhancements and fixes, device specific updates -wimax and camera, updated google apps."
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-21,
"date"="07-21",
"name"="OMFGB_desirec-1.3.0_nightly-07-21.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-21.zip",
"installable"="false",
"description"="You MUST manually wipe /system BEFORE flashing tonights build. God Mode enhancements and fixes, device specific updates -wimax and camera, updated google apps."
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-20,
"date"="07-20",
"name"="OMFGB_desirec-1.3.0_nightly-07-20.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-20.zip",
"installable"="false",
"description"="God Mode enhancements, updated theme, new wallpaper, device specific updates, etc."
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-19,
"date"="07-19",
"name"="OMFGB_desirec-1.3.0_nightly-07-19.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-19.zip",
"installable"="false",
"description"="Fixes to god mode, etc."
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-16,
"date"="07-16",
"name"="OMFGB_desirec-1.3.0_nightly-07-16.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-16.zip",
"installable"="false",
"description"="Fixes to god mode, etc."
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-15,
"date"="07-15",
"name"="OMFGB_desirec-1.3.0_nightly-07-15.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-15.zip",
"installable"="false",
"description"="Fixes to god mode, etc."
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-11,
"date"="07-11",
"name"="OMFGB_desirec-1.3.0_nightly-07-11.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-11.zip",
"installable"="false",
"description"="desirec 07-11 OMFGB 1.3.0 nightly."
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-09,
"date"="07-09",
"name"="OMFGB_desirec-1.3.0_nightly-07-09.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-09.zip",
"installable"="false",
"description"="desirec 07-09 OMFGB 1.3.0 nightly."
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-07,
"date"="07-07",
"name"="OMFGB_desirec-1.3.0_nightly-07-07.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-07.zip",
"installable"="false"
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-06,
"date"="07-06",
"name"="OMFGB_desirec-1.3.0_nightly-07-06.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-06.zip",
"installable"="false"
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-05,
"date"="07-05",
"name"="OMFGB_desirec-1.3.0_nightly-07-05.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-05.zip",
"installable"="false"
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-02,
"date"="07-02",
"name"="OMFGB_desirec-1.3.0_nightly-07-02.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-02.zip",
"installable"="false"
},
{
"device"="desirec",
"base"="1.3.0",
"version"=07-01,
"date"="07-01",
"name"="OMFGB_desirec-1.3.0_nightly-07-01.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-07-01.zip",
"installable"="false"
},
{
"device"="desirec",
"base"="1.3.0",
"version"=06-30,
"date"="06-30",
"name"="OMFGB_desirec-1.3.0_nightly-06-30.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-06-30.zip",
"installable"="false"
},
{
"device"="desirec",
"base"="1.3.0",
"version"=06-25,
"date"="06-25",
"name"="OMFGB_desirec-1.3.0_nightly-06-25.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-06-25.zip",
"installable"="false"
},
{
"device"="desirec",
"base"="1.3.0",
"version"=06-24,
"date"="06-24",
"name"="OMFGB_desirec-1.3.0_nightly-06-24.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-06-24.zip",
"installable"="false"
},
{
"device"="DesireC",
"base"="1.3.0",
"version"=06-23,
"date"="06-23",
"name"="OMFGB_desirec-1.3.0_nightly-6-23.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-06-23.zip",
"installable"="false"
},
{
"device"="DesireC",
"base"="1.3.0",
"version"=06-22,
"date"="06-22",
"name"="OMFGB_desirec-1.3.0_nightly-6-22.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-06-22.zip",
"installable"="false"
},
{
"device"="DesireC",
"base"="1.3.0",
"version"=06-21,
"date"="06-21",
"name"="OMFGB_desirec-1.3.0_nightly-6-21.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-06-21.zip",
"installable"="false"
},
{
"device"="DesireC",
"base"="1.3.0",
"version"=10,
"date"="J6/20",
"name"="OMFGB_desirec-1.3.0_nightly-10.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/desirec/OMFGB_desirec-1.3.0_nightly-10.zip",
"installable"="false"
}
]
