[
{
"device"="heroc",
"base"="1.3.0",
"version"=06-21,
"date"="06-21",
"name"="OMFGB_heroc-1.3.0_nightly-6-21.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/heroc/OMFGB_heroc-1.3.0_nightly-06-21.zip",
"installable"="false"
},
{
"device"="heroc",
"base"="1.3.0",
"version"=10,
"date"="J6/20",
"name"="OMFGB_heroc-1.3.0_nightly-10.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/heroc/OMFGB_heroc-1.3.0_nightly-10.zip",
"installable"="false"
}
]
