[
{
"device"="Incredible",
"base"="1.3.0",
"version"=10,
"date"="6/20",
"name"="OMFGB_inc-1.3.0_nightly-10.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/inc/OMFGB_inc-1.3.0_nightly-10.zip",
"installable"="false"
}
]
