[
{
"device"="Mecha",
"base"="1.3.0",
"version"=06-24,
"date"="06-24",
"name"="OMFGB_mecha-1.3.0-nightly-06-24.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mecha/OMFGB_mecha-1.3.0_nightly-06-24.zip",
"installable"="false"
},
{
"device"="Mecha",
"base"="1.3.0",
"version"=4,
"date"="June 11, 2011",
"url"="http://r2doesinc.bitsurge.net/nightlies/mecha/OMFGB_mecha-1.3.0_nightly-4.zip",
"installable"="false"
}
]