[
{
"device"="mesmerizemtd",
"base"="1.3.1",
"version"=09-21,
"date"="09-21",
"name"="OMFGB_mesmerizemtd-1.3.1_nightly-09-21.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mesmerizemtd/OMFGB_mesmerizemtd-1.3.1_nightly-09-21.zip",
"installable"="false",
"description"="DX updated to GB kernel. Mecha converted to ext4. New lockscreen music controls. Fixed status bar music controls. TTF for motot devices...etc"
},
{
"device"="mesmerizemtd",
"base"="1.3.1",
"version"=09-14,
"date"="09-14",
"name"="OMFGB_mesmerizemtd-1.3.1_nightly-09-14.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mesmerizemtd/OMFGB_mesmerizemtd-1.3.1_nightly-09-14.zip",
"installable"="false",
"description"="So much I dont even know what, but it also includes the Sense 3.0 and new Honeycomb Lockscreen"
},
{
"device"="mesmerizemtd",
"base"="1.3.1",
"version"=08-25,
"date"="08-25",
"name"="OMFGB_mesmerizemtd-1.3.1_nightly-08-25.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mesmerizemtd/OMFGB_mesmerizemtd-1.3.1_nightly-08-25.zip",
"installable"="false",
"description"="Fucking tons and tons. Touchwiz style notification shade music controls, many new tweaks from Roman --including the center clock mod--. Add Vibrant to list of supported devices. Fix Samsung lights sensor --I think--. Added touch to focus in the Camera for supported devices."
},
{
"device"="mesmerizemtd",
"base"="1.3.1",
"version"=08-22,
"date"="08-22",
"name"="OMFGB_mesmerizemtd-1.3.1_nightly-08-22.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mesmerizemtd/OMFGB_mesmerizemtd-1.3.1_nightly-08-22.zip",
"installable"="false",
"description"="Added options to hide 3/4g and sync icon. Added 160 character split to the MMS app. BT now sends song metadata to BT stereos."
},
{
"device"="mesmerizemtd",
"base"="1.3.1",
"version"=08-21,
"date"="08-21",
"name"="OMFGB_mesmerizemtd-1.3.1_nightly-08-21.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mesmerizemtd/OMFGB_mesmerizemtd-1.3.1_nightly-08-21.zip",
"installable"="false",
"description"="Many fixes to all of the Samsung devices, new settings for hiding more icons in the status bar. Fixes for Lockscreen Settings FC."
},
{
"device"="mesmerizemtd",
"base"="1.3.1",
"version"=08-19,
"date"="08-19",
"name"="OMFGB_mesmerizemtd-1.3.1_nightly-08-19.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mesmerizemtd/OMFGB_mesmerizemtd-1.3.1_nightly-08-19.zip",
"installable"="false",
"description"="Automatic check for updates and notification upon updates to Nightlies, Addons, OMGB Builds, and alerts. Sense 3.0 Lockscreen coming soon."
},
{
"device"="mesmerizemtd",
"base"="1.3.1",
"version"=08-11,
"date"="08-11",
"name"="OMFGB_mesmerizemtd-1.3.1_nightly-08-11.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mesmerizemtd/OMFGB_mesmerizemtd-1.3.1_nightly-08-11.zip",
"installable"="false",
"description"="Cleaned up a ton of code and fix issues with the lockscreens and batteries in God Mode. Update kernel for MUCH louder in call audio for mecha. Many AOSP updates."
},
{
"device"="mesmerizemtd",
"base"="1.3.1",
"version"=08-10,
"date"="08-10",
"name"="OMFGB_mesmerizemtd-1.3.1_nightly-08-10.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mesmerizemtd/OMFGB_mesmerizemtd-1.3.1_nightly-08-10.zip",
"installable"="false",
"description"="Cleaned up a ton of code and fix issues with the lockscreens and batteries in God Mode."
},
{
"device"="mesmerizemtd",
"base"="1.3.1",
"version"=08-02,
"date"="08-02",
"name"="OMFGB_mesmerizemtd-1.3.1_nightly-08-02.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mesmerizemtd/OMFGB_mesmerizemtd-1.3.1_nightly-08-02.zip",
"installable"="false",
"description"="MIUI Battery color changing, Google apps flashing option, Droid X fixes, Netflix fixed."
},
{
"device"="mesmerizemtd",
"base"="1.3.1",
"version"=07-31,
"date"="07-31",
"name"="OMFGB_mesmerizemtd-1.3.1_nightly-07-31.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mesmerizemtd/OMFGB_mesmerizemtd-1.3.1_nightly-07-31.zip",
"installable"="false",
"description"="Droid X added. Added 1% battery increments since last DX beta. New Launcher speed tweak from Jt1134. In call audio tweaks to Tunderbolt. Fix Fascinate wifi?"
},
{
"device"="mesmerizemtd",
"base"="1.3.1",
"version"=07-30,
"date"="07-30",
"name"="OMFGB_mesmerizemtd-1.3.1_nightly-07-30.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mesmerizemtd/OMFGB_mesmerizemtd-1.3.1_nightly-07-30.zip",
"installable"="false",
"description"="4G LTE Toggle included. Broken MMS fixed."
},
{
"device"="mesmerizemtd",
"base"="1.3.1",
"version"=07-28,
"date"="07-28",
"name"="OMFGB_mesmerizemtd-1.3.1_nightly-07-28.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mesmerizemtd/OMFGB_mesmerizemtd-1.3.1_nightly-07-28.zip",
"installable"="false",
"description"="Update to OMFGB 1.3.1. Update to Android 2.3.5. Fix wifi tether for applicable devices. Fixes for Google apps instalation issues for Sholes."
},
{
"device"="mesmerizemtd",
"base"="1.3.0",
"version"=07-24,
"date"="07-24",
"name"="OMFGB_mesmerizemtd-1.3.0_nightly-07-24.zip",
"url"="http://dl.dropbox.com/u/29062346/Showcase/Roms/OMFGB_mesmerizemtd-1.3.0_nightly-07-24.zip",
"installable"="false",
"description"="We did stuff."
},
{
"device"="mesmerizemtd",
"base"="1.3.0",
"version"=07-21,
"date"="07-21",
"name"="OMFGB_mesmerizemtd-1.3.0_nightly-07-21.zip",
"url"="http://dl.dropbox.com/u/29062346/Showcase/Roms/OMFGB_mesmerizemtd-1.3.0_nightly-07-21.zip",
"installable"="false",
"description"="You MUST manually wipe /system BEFORE flashing tonights build. God Mode enhancements and fixes, device specific updates -wimax and camera, updated google apps."
},
{
"device"="mesmerizemtd",
"base"="1.3.0",
"version"=07-20,
"date"="07-20",
"name"="OMFGB_mesmerizemtd-1.3.0_nightly-07-20.zip",
"url"="http://dl.dropbox.com/u/29062346/Showcase/Roms/OMFGB_mesmerizemtd-1.3.0_nightly-07-20.zip",
"installable"="false",
"description"="God Mode enhancements, updated theme, new wallpaper, device specific updates, etc."
},
{
"device"="mesmerizemtd",
"base"="1.3.0",
"version"=07-19,
"date"="07-19",
"name"="OMFGB_mesmerizemtd-1.3.0_nightly-07-19.zip",
"url"="http://dl.dropbox.com/u/29062346/Showcase/Roms/OMFGB_mesmerizemtd-1.3.0_nightly-07-19.zip",
"installable"="false",
"description"=""
},
]
