[
{
"device"="mesmerizemtd",
"base"="1.3.1",
"version"=07-30,
"date"="07-30",
"name"="OMFGB_mesmerizemtd-1.3.1_nightly-07-30.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mesmerizemtd/OMFGB_mesmerizemtd-1.3.1_nightly-07-30.zip",
"installable"="false",
"description"="4G LTE Toggle included. Broken MMS fixed."
},
{
"device"="mesmerizemtd",
"base"="1.3.1",
"version"=07-28,
"date"="07-28",
"name"="OMFGB_mesmerizemtd-1.3.1_nightly-07-28.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/mesmerizemtd/OMFGB_mesmerizemtd-1.3.1_nightly-07-28.zip",
"installable"="false",
"description"="Update to OMFGB 1.3.1. Update to Android 2.3.5. Fix wifi tether for applicable devices. Fixes for Google apps instalation issues for Sholes."
},
{
"device"="mesmerizemtd",
"base"="1.3.0",
"version"=07-24,
"date"="07-24",
"name"="OMFGB_mesmerizemtd-1.3.0_nightly-07-24.zip",
"url"="http://dl.dropbox.com/u/29062346/Showcase/Roms/OMFGB_mesmerizemtd-1.3.0_nightly-07-24.zip",
"installable"="false",
"description"="We did stuff."
},
{
"device"="mesmerizemtd",
"base"="1.3.0",
"version"=07-21,
"date"="07-21",
"name"="OMFGB_mesmerizemtd-1.3.0_nightly-07-21.zip",
"url"="http://dl.dropbox.com/u/29062346/Showcase/Roms/OMFGB_mesmerizemtd-1.3.0_nightly-07-21.zip",
"installable"="false",
"description"="You MUST manually wipe /system BEFORE flashing tonights build. God Mode enhancements and fixes, device specific updates -wimax and camera, updated google apps."
},
{
"device"="mesmerizemtd",
"base"="1.3.0",
"version"=07-20,
"date"="07-20",
"name"="OMFGB_mesmerizemtd-1.3.0_nightly-07-20.zip",
"url"="http://dl.dropbox.com/u/29062346/Showcase/Roms/OMFGB_mesmerizemtd-1.3.0_nightly-07-20.zip",
"installable"="false",
"description"="God Mode enhancements, updated theme, new wallpaper, device specific updates, etc."
},
{
"device"="mesmerizemtd",
"base"="1.3.0",
"version"=07-19,
"date"="07-19",
"name"="OMFGB_mesmerizemtd-1.3.0_nightly-07-19.zip",
"url"="http://dl.dropbox.com/u/29062346/Showcase/Roms/OMFGB_mesmerizemtd-1.3.0_nightly-07-19.zip",
"installable"="false",
"description"=""
},
]
