[
{
"device"="sholes",
"base"="1.3.1",
"version"=09-14,
"date"="09-14",
"name"="OMFGB_sholes-1.3.1_nightly-09-14.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.1_nightly-09-14.zip",
"installable"="false",
"description"="So much I dont even know what, but it also includes the Sense 3.0 and new Honeycomb Lockscreen"
},
{
"device"="sholes",
"base"="1.3.1",
"version"=08-25,
"date"="08-25",
"name"="OMFGB_sholes-1.3.1_nightly-08-25.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.1_nightly-08-25.zip",
"installable"="false",
"description"="Fucking tons and tons. Touchwiz style notification shade music controls, many new tweaks from Roman --including the center clock mod--. Add Vibrant to list of supported devices. Fix Samsung lights sensor --I think--. Added touch to focus in the Camera for supported devices."
},
{
"device"="sholes",
"base"="1.3.1",
"version"=08-23,
"date"="08-23",
"name"="OMFGB_sholes-1.3.1_nightly-08-23.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.1_nightly-08-23.zip",
"installable"="false",
"description"="Welcome Roman to the T3hh4xx0r Developer Team. Fix four hotseat landscape layout. Laid groundwork for Touchwiz style notification pull down music controls (coming soon)."
},
{
"device"="sholes",
"base"="1.3.1",
"version"=08-22,
"date"="08-22",
"name"="OMFGB_sholes-1.3.1_nightly-08-22.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.1_nightly-08-22.zip",
"installable"="false",
"description"="Added options to hide 3/4g and sync icon. Added 160 character split to the MMS app. BT now sends song metadata to BT stereos."
},
{
"device"="sholes",
"base"="1.3.1",
"version"=08-21,
"date"="08-21",
"name"="OMFGB_sholes-1.3.1_nightly-08-21.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.1_nightly-08-21.zip",
"installable"="false",
"description"="Many fixes to all of the Samsung devices, new settings for hiding more icons in the status bar. Fixes for Lockscreen Settings FC."
},
{
"device"="sholes",
"base"="1.3.1",
"version"=08-17,
"date"="08-17",
"name"="OMFGB_sholes-1.3.1_nightly-08-17.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.1_nightly-08-17.zip",
"installable"="false",
"description"="Automatic check for updates and notification upon updates to Nightlies, Addons, OMGB Builds, and alerts. Sense 3.0 Lockscreen coming soon."
},
{
"device"="sholes",
"base"="1.3.1",
"version"=08-12,
"date"="08-12",
"name"="OMFGB_sholes-1.3.1_nightly-08-12.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.1_nightly-08-12.zip",
"installable"="false",
"description"="Fixed broken usb mounting from last night. More God Mode updates to clean and organize settings. Totally brand new Bulletin Board concept in God Mode."
},
{
"device"="sholes",
"base"="1.3.1",
"version"=08-11,
"date"="08-11",
"name"="OMFGB_sholes-1.3.1_nightly-08-11.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.1_nightly-08-11.zip",
"installable"="false",
"description"="Cleaned up a ton of code and fix issues with the lockscreens and batteries in God Mode. Update kernel for MUCH louder in call audio for mecha. Many AOSP updates."
},
{
"device"="sholes",
"base"="1.3.1",
"version"=08-10,
"date"="08-10",
"name"="OMFGB_sholes-1.3.1_nightly-08-10.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.1_nightly-08-10.zip",
"installable"="false",
"description"="Cleaned up a ton of code and fix issues with the lockscreens and batteries in God Mode."
},
{
"device"="sholes",
"base"="1.3.1",
"version"=08-08,
"date"="08-08",
"name"="OMFGB_sholes-1.3.1_nightly-08-08.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.1_nightly-08-08.zip",
"installable"="false",
"description"="Idk, we did a bunch of stuff. Fixed a lot of device specific stuff."
},
{
"device"="sholes",
"base"="1.3.1",
"version"=08-02,
"date"="08-02",
"name"="OMFGB_sholes-1.3.1_nightly-08-02.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.1_nightly-08-02.zip",
"installable"="false",
"description"="MIUI Battery color changing, Google apps flashing option, Droid X fixes, Netflix fixed."
},
{
"device"="sholes",
"base"="1.3.1",
"version"=07-31,
"date"="07-31",
"name"="OMFGB_sholes-1.3.1_nightly-07-31.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.1_nightly-07-31.zip",
"installable"="false",
"description"="Droid X added. Added 1% battery increments since last DX beta. New Launcher speed tweak from Jt1134. In call audio tweaks to Tunderbolt. Fix Fascinate wifi?"
},
{
"device"="sholes",
"base"="1.3.1",
"version"=07-30,
"date"="07-30",
"name"="OMFGB_sholes-1.3.1_nightly-07-30.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.1_nightly-07-30.zip",
"installable"="false",
"description"="4G LTE Toggle included. Broken MMS fixed."
},
{
"device"="sholes",
"base"="1.3.1",
"version"=07-28,
"date"="07-28",
"name"="OMFGB_sholes-1.3.1_nightly-07-28.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.1_nightly-07-28.zip",
"installable"="false",
"description"="Update to OMFGB 1.3.1. Update to Android 2.3.5. Fix wifi tether for applicable devices. Fixes for Google apps instalation issues for Sholes."
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-25,
"date"="07-25",
"name"="OMFGB_sholes-1.3.0_nightly-07-25.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-25.zip",
"installable"="false",
"description"="Updates for Mecha data, notification light while charging. Add Showcase and Mesmerize builds. Fix God mode related FCs. New features to God Mode."
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-24,
"date"="07-24",
"name"="OMFGB_sholes-1.3.0_nightly-07-24.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-24.zip",
"installable"="false",
"description"="We did stuff."
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-23,
"date"="07-23",
"name"="OMFGB_sholes-1.3.0_nightly-07-23.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-23.zip",
"installable"="false",
"description"="You MUST manually wipe /system BEFORE flashing tonights build. God Mode enhancements and fixes, device specific updates -wimax and camera, updated google apps."
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-21,
"date"="07-21",
"name"="OMFGB_sholes-1.3.0_nightly-07-21.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-21.zip",
"installable"="false",
"description"="You MUST manually wipe /system BEFORE flashing tonights build. God Mode enhancements and fixes, device specific updates -wimax and camera, updated google apps."
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-20,
"date"="07-20",
"name"="OMFGB_sholes-1.3.0_nightly-07-20.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-20.zip",
"installable"="false",
"description"="God Mode enhancements, updated theme, new wallpaper, device specific updates, etc."
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-19,
"date"="07-19",
"name"="OMFGB_sholes-1.3.0_nightly-07-19.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-19.zip",
"installable"="false",
"description"="Fixes to god mode, etc."
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-16,
"date"="07-16",
"name"="OMFGB_sholes-1.3.0_nightly-07-16.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-16.zip",
"installable"="false",
"description"="Fixes to god mode, etc."
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-15,
"date"="07-15",
"name"="OMFGB_sholes-1.3.0_nightly-07-15.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-15.zip",
"installable"="false",
"description"="Fixes to god mode, etc."
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-11,
"date"="07-11",
"name"="OMFGB_sholes-1.3.0_nightly-07-11.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-11.zip",
"installable"="false",
"description"="sholes 07-11 OMFGB 1.3.0 nightly."
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-09,
"date"="07-09",
"name"="OMFGB_sholes-1.3.0_nightly-07-09.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-09.zip",
"installable"="false",
"description"="sholes 07-09 OMFGB 1.3.0 nightly."
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-07,
"date"="07-07",
"name"="OMFGB_sholes-1.3.0_nightly-07-07.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-07.zip",
"installable"="false"
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-06,
"date"="07-06",
"name"="OMFGB_sholes-1.3.0_nightly-07-06.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-06.zip",
"installable"="false"
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-05,
"date"="07-05",
"name"="OMFGB_sholes-1.3.0_nightly-07-05.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-05.zip",
"installable"="false"
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-02,
"date"="07-02",
"name"="OMFGB_sholes-1.3.0_nightly-07-02.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-02.zip",
"installable"="false"
},
{
"device"="sholes",
"base"="1.3.0",
"version"=07-01,
"date"="07-01",
"name"="OMFGB_sholes-1.3.0_nightly-07-01.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-07-01.zip",
"installable"="false"
},
{
"device"="sholes",
"base"="1.3.0",
"version"=06-30,
"date"="06-30",
"name"="OMFGB_sholes-1.3.0_nightly-06-30.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-06-30.zip",
"installable"="false"
},
{
"device"="sholes",
"base"="1.3.0",
"version"=06-29,
"date"="06-29",
"name"="OMFGB_sholes-1.3.0_nightly-06-29.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-06-29.zip",
"installable"="false"
},
{
"device"="sholes",
"base"="1.3.0",
"version"=06-27,
"date"="06-27",
"name"="OMFGB_sholes-1.3.0_nightly-06-27.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-06-27.zip",
"installable"="false"
},
{
"device"="sholes",
"base"="1.3.0",
"version"=06-25,
"date"="06-25",
"name"="OMFGB_sholes-1.3.0_nightly-06-25.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-06-25.zip",
"installable"="false"
},
{
"device"="sholes",
"base"="1.3.0",
"version"=06-24,
"date"="06-24",
"name"="OMFGB_sholes-1.3.0_nightly-06-24.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-06-24.zip",
"installable"="false"
},
{
"device"="Sholes",
"base"="1.3.0",
"version"=06-21,
"date"="06-21",
"name"="OMFGB_sholes-1.3.0_nightly-6-21.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-06-21.zip",
"installable"="false"
},
{
"device"="Sholes",
"base"="1.3.0",
"version"=10,
"date"="June 20, 2011",
"name"="OMFGB_sholes-1.3.0_nightly-10.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/sholes/OMFGB_sholes-1.3.0_nightly-10.zip",
"installable"="false"
}
]
