[
{
"device"="supersonic",
"base"="1.3.1",
"version"=07-28,
"date"="07-28",
"name"="OMFGB_supersonic-1.3.1_nightly-07-28.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/supersonic/OMFGB_supersonic-1.3.1_nightly-07-28.zip",
"installable"="false",
"description"="Update to OMFGB 1.3.1. Update to Android 2.3.5. Fix wifi tether for applicable devices. Fixes for Google apps instalation issues for Sholes."
},
{
"device"="supersonic",
"base"="1.3.0",
"version"=07-24,
"date"="07-24",
"name"="OMFGB_supersonic-1.3.0_nightly-07-24.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/supersonic/OMFGB_supersonic-1.3.0_nightly-07-24.zip",
"installable"="false",
"description"="We did stuff."
},
{
"device"="supersonic",
"base"="1.3.0",
"version"=07-23,
"date"="07-23",
"name"="OMFGB_supersonic-1.3.0_nightly-07-23.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/supersonic/OMFGB_supersonic-1.3.0_nightly-07-23.zip",
"installable"="false",
"description"="You MUST manually wipe /system BEFORE flashing tonights build. God Mode enhancements and fixes, device specific updates -wimax and camera, updated google apps."
},
{
"device"="supersonic",
"base"="1.3.0",
"version"=07-21,
"date"="07-21",
"name"="OMFGB_supersonic-1.3.0_nightly-07-21.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/supersonic/OMFGB_supersonic-1.3.0_nightly-07-21.zip",
"installable"="false",
"description"="You MUST manually wipe /system BEFORE flashing tonights build. God Mode enhancements and fixes, device specific updates -wimax and camera, updated google apps."
},
{
"device"="supersonic",
"base"="1.3.0",
"version"=07-20,
"date"="07-20",
"name"="OMFGB_supersonic-1.3.0_nightly-07-20.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/supersonic/OMFGB_supersonic-1.3.0_nightly-07-20.zip",
"installable"="false",
"description"="God Mode enhancements, updated theme, new wallpaper, device specific updates, etc."
},
{
"device"="supersonic",
"base"="1.3.0",
"version"=07-19,
"date"="07-19",
"name"="OMFGB_supersonic-1.3.0_nightly-07-19.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/supersonic/OMFGB_supersonic-1.3.0_nightly-07-19.zip",
"installable"="false",
"description"="Fixes to god mode, etc."
},
{
"device"="supersonic",
"base"="1.3.0",
"version"=07-11,
"date"="07-11",
"name"="OMFGB_supersonic-1.3.0_nightly-07-11.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/supersonic/OMFGB_supersonic-1.3.0_nightly-07-11.zip",
"installable"="false",
"description"="supersonic 07-11 OMFGB 1.3.0 nightly."
},
{
"device"="supersonic",
"base"="1.3.0",
"version"=07-09,
"date"="07-09",
"name"="OMFGB_supersonic-1.3.0_nightly-07-09.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/supersonic/OMFGB_supersonic-1.3.0_nightly-07-09.zip",
"installable"="false",
"description"="supersonic 07-09 OMFGB 1.3.0 nightly."
},
{
"device"="supersonic",
"base"="1.3.0",
"version"=07-07,
"date"="07-07",
"name"="OMFGB_supersonic-1.3.0_nightly-07-07.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/supersonic/OMFGB_supersonic-1.3.0_nightly-07-07.zip",
"installable"="false"
},
{
"device"="supersonic",
"base"="1.3.0",
"version"=07-06,
"date"="07-06",
"name"="OMFGB_supersonic-1.3.0_nightly-07-06.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/supersonic/OMFGB_supersonic-1.3.0_nightly-07-06.zip",
"installable"="false"
},
{
"device"="supersonic",
"base"="1.3.0",
"version"=07-05,
"date"="07-05",
"name"="OMFGB_supersonic-1.3.0_nightly-07-05.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/supersonic/OMFGB_supersonic-1.3.0_nightly-07-05.zip",
"installable"="false"
},
{
"device"="supersonic",
"base"="1.3.0",
"version"=07-02,
"date"="07-02",
"name"="OMFGB_supersonic-1.3.0_nightly-07-02.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/supersonic/OMFGB_supersonic-1.3.0_nightly-07-02.zip",
"installable"="false"
},
{
"device"="Supersonic",
"base"="1.3.0",
"version"=4,
"date"="Some date",
"name"="OMFGB_inc-1.3.0_nightly-4.zip",
"url"="http://r2doesinc.bitsurge.net/nightlies/supersonic/OMFGB_supersonic-1.3.0_nightly-4.zip",
"installable"="false"
},
]